name: Build Monke Adventures

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build Fat JAR
        # На Windows сам запуск через ./gradlew может тупить в обычном shell
        run: ./gradlew fatJar --stacktrace

      - name: Package with jpackage (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist
          $jarFile = Get-ChildItem -Path build/libs/*.jar | Where-Object { $_.Name -like "*all.jar" } | Select-Object -First 1
          if (-not $jarFile) { throw "JAR not found!" }
          
          jpackage `
            --type exe `
            --input build/libs `
            --name "MonkeAdventures" `
            --main-jar $($jarFile.Name) `
            --main-class ru.nsu.ccfit.alarkhipov.monkeadventures.Main `
            --dest dist `
            --vendor "Alarkhipov" `
            --app-version "1.0.0" `
            --win-shortcut `
            --win-menu

      - name: Package with jpackage (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist
          JAR_NAME=$(basename $(ls build/libs/*all.jar | head -n 1))
          jpackage \
            --input build/libs \
            --name "MonkeAdventures" \
            --main-jar "$JAR_NAME" \
            --main-class ru.nsu.ccfit.alarkhipov.monkeadventures.Main \
            --dest dist \
            --vendor "Alarkhipov" \
            --app-version "1.0.0"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MonkeAdventures-${{ matrix.os }}
          path: dist/
